### ISSUE TITLE
run_rr.py not found (documentation issue)

### ISSUE THREAD

**Issue by KatharinaHoff** [AntonBankevich/DR#2]
I much appreciate that you developed LJA, and I read the preprint with interest after hearing about LJA at PAG.

Following your installation guidelines, my job died with the following error:

```
sh: 1: run_rr.py: not found
```

This script is available in `DR/py`, which I had not added to my PATH because I was unaware that I should do it.  It would be great if you added the info at https://github.com/AntonBankevich/DR/blob/master/docs/lja_manual.md to help other users. Also, it might be helpful to tell users to make that script executable by e.g. `chmod u+x DR/py`. (Cloning from github resulted in a lack of the executability property). 

I correct myself: the list of rquired python modules is actually present. Sorry that I overlooked it ;-)

**Comment by AntonBankevich** [comment]
Hi! Thank you for your interest in LJA! It seems like you forgot to run "make install" and that is why you had to modify your PATH variable. However I strongly recommend to use our latest release that does not contain python code at all and where we got rid of make install and all these dependencies (not to mention a lot of fixed bugs).

**Comment by AntonBankevich** [comment]
Oh. Also I did not realize: this is not an LJA repositorium! Please see https://github.com/AntonBankevich/LJA . This is an old superproject where I keep the code I intend to reuse in other projects and LJA manual got here by accident.

**Comment by KatharinaHoff** [comment]
Thank you so much 🤣 I was wondering why I have python code in the latest
pull while you say it’s not there anymore.

Correct, I don’t run make install in non-root environments… I don’t
routinely develop with cmake and was too lazy to check how to change the
install prefix path. Usually adding binaries to path is sufficient… My own
fault obviously. I will obtain the correct version and give it another try.
